name: elis_analytics_dashboard
description: ELIS responsive analytics dashboard
publish_to: 'none'  # DO NOT REMOVE
version: 1.1.0-beta.4.1

environment:
  sdk: ^2.14.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_core: ^19.3.48
  syncfusion_flutter_charts: ^19.3.48
  syncfusion_flutter_maps: ^19.3.48-beta
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.8
  weather_icons: ^3.0.0
  mutex: ^3.0.0
  intl: ^0.17.0
  http: ^0.13.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/font/
    - asset/font/OpenSans/
    - asset/image/
    - asset/license/
    - asset/license/OpenSans/
    - asset/license/GDPR/
    - asset/license/Creator/
    - asset/map/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: asset/font/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: asset/font/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: asset/font/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: asset/font/OpenSans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: asset/font/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: asset/font/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: asset/font/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: asset/font/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: asset/font/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: asset/font/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
